#!/bin/sh

# PROVIDE: ec2_user_data
# BEFORE: rsyslogd syslogd
# REQUIRE: netwait

# download user-data and run its content as sh. currently, user-data is used to
# set hostname before bootstrapping.
#
# TODO
# - there should be a better way to set hostname (tags:Name?)

: ${ec2_user_data_enable=YES}

. /etc/rc.subr

name="ec2_user_data"
rcvar=`set_rcvar`
start_cmd="ec2_user_data_run"
stop_cmd=":"

ec2_user_data_run()
{
   fetch -q -o - http://169.254.169.254/latest/user-data | sh -
}

load_rc_config $name
run_rc_command "$1"
