#!/bin/sh
#
# PROVIDE: pf_reload
# REQUIRE: pf
#
# fetches VPC's IPv4 CIDR and reload pf

: ${pf_reload_enable=YES}

. /etc/rc.subr

name="pf_reload"
rcvar=`set_rcvar`
start_cmd="pf_reload_run"
stop_cmd=":"

pf_reload_run()
{
    EC2_MAC=`/usr/bin/fetch -qo - http://169.254.169.254/latest/meta-data/mac`
    EC2_VPC_IPV4_CIDR_BLOCK=`/usr/bin/fetch -qo  http://169.254.169.254/latest/meta-data/network/interfaces/macs/${EC2_MAC}/vpc-ipv4-cidr-block`
    /sbin/pfctl -D vpc_network=${EC2_VPC_IPV4_CIDR_BLOCK} -f /etc/pf.conf
}

load_rc_config $name
run_rc_command "$1"

